server:
  port: 8889

management:
  context-path: /admin
  
logging:
  level:
    org.springframework.cloud: 'DEBUG'
    
spring:
  application:
    name: configserver-client
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: dev
