server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/exampledriven/config-server-repo.git
#          basedir: target/config
        native:
          searchLocations: file:properties
  profiles:
    active: native
---
#spring:
#  profiles: cloud
#eureka:
#  password: password
#  instance:
#    hostname: ${vcap.application.uris[0]}
#    nonSecurePort: 80
#  client:
#    serviceUrl:
#      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/
#
#---
#spring:
#  profiles: lattice
#  cloud:
#    config:
#      server:
#        overrides:
#          eureka:
#            client:
#              serviceUrl:
#                defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
#            instance:
#              hostname: $\{CF_INSTANCE_IP:localhost}
#              nonSecurePort: $\{CF_INSTANCE_PORT:$\{PORT:$\{server.port:8080}}}
#eureka:
#  instance:
#    hostname: ${CF_INSTANCE_IP:localhost}
#    nonSecurePort: ${CF_INSTANCE_PORT:${PORT:${server.port:8888}}}
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

